### Get all content
GET http://localhost:8081/content
Accept: application/json
#Authorization: Bearer c2VjcmV0a2V5MTIzNDU2

### Create new content
POST http://localhost:8081/content
Content-Type: application/json

{
  "userId": 3,
  "title": "My newly created Recipe",
  "description": "This is the 2nd recipe description",
  "status": "IDEA",
  "contentType": "ARTICLE",
  "dateCreated": "2024-08-30T11:24:19.469842",
  "dateUpdated": null,
  "url": ""
}

### Update content
PUT http://localhost:8081/content/6
Content-Type: application/json

{
  "title": "Updated Recipe",
  "description": "Updated description",
  "status": "PUBLISHED",
  "contentType": "ARTICLE",
  "dateCreated": "2024-08-30T11:24:19.4698425",
  "dateUpdated": "2024-09-01T11:24:19.4698425",
  "url": "updated-url"
}

### Delete content
DELETE http://localhost:8081/content/6

### Get content by user ID
GET http://localhost:8081/content/user/2
Accept: application/json

### Get number of contents by status
GET http://localhost:8081/content/count/status?status=IDEA
Accept: application/json

### Get number of contents by type by user
GET http://localhost:8081/content/count/type?userId=2&type=ARTICLE
Accept: application/json

### Get all content by type
GET http://localhost:8081/content/type/ARTICLE
Accept: application/json

### Get number of content by user by status
GET http://localhost:8081/content/user/2/status/IDEA
Accept: application/json

### Get number of content by type
GET http://localhost:8081/content/count/type/ARTICLE
Accept: application/json